"use client";

import { useState } from "react";
import { ArrowDownUp, ChevronLeft, ChevronRight, CircleAlert, Eye, Pencil, Plus, RefreshCw, Search, SlidersHorizontal, Trash2, Users, X } from "lucide-react";
import { useDashboard } from "@/components/dashboard/provider";
import { PriorityBadge, Score, StatusBadge } from "@/components/ui/lead-badges";
import { initials, services, statuses, titleCase } from "@/lib/utils";
import type { Lead } from "@/lib/types";
import type { LeadDialogState } from "./lead-dialog";

export function LeadList({ onAction }: { onAction: (state: LeadDialogState) => void }) {
  const { leads, search, setSearch, loading, refreshing, error, refresh } = useDashboard();
  const [priority, setPriority] = useState("");
  const [status, setStatus] = useState("");
  const [service, setService] = useState("");
  const [sort, setSort] = useState("name");
  const [page, setPage] = useState(1);
  const query = search.trim().toLowerCase();
  const filtered = leads.filter(lead => (!priority || lead.priority === priority) && (!status || lead.state.toLowerCase() === status) && (!service || lead.service.toLowerCase() === service.toLowerCase()) && [lead.name, lead.email, lead.phone, lead.service].some(value => value.toLowerCase().includes(query))).sort((a, b) => sort === "score" ? (b.score ?? -1) - (a.score ?? -1) : a.name.localeCompare(b.name));
  const pageCount = Math.max(1, Math.ceil(filtered.length / 8));
  const currentPage = Math.min(page, pageCount);
  const visible = filtered.slice((currentPage - 1) * 8, currentPage * 8);
  const activeFilters = Boolean(priority || status || service || search);
  const serviceOptions = Array.from(new Set([...services, ...leads.map(lead => lead.service).filter(Boolean)]));
  const statusOptions = Array.from(new Set([...statuses, ...leads.map(lead => lead.state.toLowerCase())]));
  const reset = () => { setPriority(""); setStatus(""); setService(""); setSearch(""); setPage(1); };
  function actions(lead: Lead) { return <div className="row-actions"><button className="icon-button" title="View lead" aria-label={`View ${lead.name}`} onClick={() => onAction({ mode: "view", lead })}><Eye size={16} /></button><button className="icon-button" title="Edit lead" aria-label={`Edit ${lead.name}`} onClick={() => onAction({ mode: "edit", lead })}><Pencil size={15} /></button><button className="icon-button danger-icon" title="Delete lead" aria-label={`Delete ${lead.name}`} onClick={() => onAction({ mode: "delete", lead })}><Trash2 size={15} /></button></div>; }
  return <section className="leads-panel" aria-label="Leads"><div className="panel-heading"><div><h2>All leads {!loading && <span className="count-chip">{leads.length}</span>}</h2><p>Your relationships, all in one place.</p></div><button className="button subtle" onClick={() => void refresh()} disabled={refreshing}><RefreshCw size={15} className={refreshing ? "spin" : ""} />Refresh</button></div>
    <div className="filters"><label className="search table-search"><Search size={17} /><input aria-label="Search leads by name, email, phone, or service" placeholder="Search by name, email, phone…" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /></label><div className="filter-controls"><SlidersHorizontal size={16} className="filter-icon" /><select aria-label="Filter by priority" value={priority} onChange={event => { setPriority(event.target.value); setPage(1); }}><option value="">All priorities</option>{["high", "medium", "low"].map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select><select aria-label="Filter by status" value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{statusOptions.map(value => <option key={value} value={value}>{titleCase(value)}</option>)}</select><select aria-label="Filter by service" value={service} onChange={event => { setService(event.target.value); setPage(1); }}><option value="">All services</option>{serviceOptions.map(value => <option key={value}>{value}</option>)}</select>{activeFilters && <button className="icon-button" aria-label="Clear filters" onClick={reset}><X size={16} /></button>}</div></div>
    {error && <div className="error-banner" role="alert"><CircleAlert size={20} /><div><strong>Unable to load your workspace.</strong><p>{error}{leads.length > 0 && " Showing previously loaded data."}</p></div><button className="button" disabled={refreshing} onClick={() => void refresh()}>Try Again</button></div>}
    {loading ? <div className="table-skeleton" aria-label="Loading leads" aria-busy="true">{Array.from({ length: 6 }, (_, index) => <div className="skeleton-row" key={index}><div className="skeleton skeleton-avatar" /><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /></div>)}</div> : filtered.length ? <>
      <div className="table-scroll"><table><thead><tr><th><button className="sort-button" onClick={() => { setSort(sort === "name" ? "score" : "name"); setPage(1); }}>Lead <ArrowDownUp size={12} /></button></th><th>Email</th><th>Phone</th><th>Service</th><th>Status</th><th><button className="sort-button" onClick={() => { setSort("score"); setPage(1); }}>AI Score <ArrowDownUp size={12} /></button></th><th>Priority</th><th className="actions-heading">Actions</th></tr></thead><tbody>{visible.map(lead => <tr key={lead.email}><td><button className="lead-identity" onClick={() => onAction({ mode: "view", lead })}><span className="lead-avatar">{initials(lead.name)}</span><span><strong>{lead.name}</strong><small>{lead.email}</small></span></button></td><td className="muted">{lead.email}</td><td className="phone-cell">{lead.phone || "—"}</td><td><span className="service-label">{lead.service || "—"}</span></td><td><StatusBadge state={lead.state} /></td><td><Score score={lead.score} /></td><td><PriorityBadge priority={lead.priority} /></td><td>{actions(lead)}</td></tr>)}</tbody></table></div>
      <div className="mobile-leads">{visible.map(lead => <article className="mobile-lead" key={lead.email}><div className="mobile-lead-top"><button className="lead-identity" onClick={() => onAction({ mode: "view", lead })}><span className="lead-avatar">{initials(lead.name)}</span><span><strong>{lead.name}</strong><small>{lead.email}</small></span></button><StatusBadge state={lead.state} /></div><div className="mobile-lead-meta"><span>{lead.service}</span><span>{lead.phone}</span></div><div className="mobile-lead-bottom"><Score score={lead.score} /><PriorityBadge priority={lead.priority} />{actions(lead)}</div></article>)}</div>
    </> : !error && <div className="empty-state"><span className="empty-icon"><Users size={28} /></span><h3>No leads found</h3><p>{activeFilters ? "Try another search or clear your filters to see more leads." : "Every opportunity starts with a connection. Add your first lead."}</p><button className="button primary" onClick={() => activeFilters ? reset() : onAction({ mode: "create" })}>{activeFilters ? <X size={16} /> : <Plus size={16} />}{activeFilters ? "Clear filters" : "Add your first lead"}</button></div>}
    <div className="table-footer"><span>{loading ? "Loading your pipeline…" : `Showing ${filtered.length ? (currentPage - 1) * 8 + 1 : 0}–${Math.min(currentPage * 8, filtered.length)} of ${filtered.length} leads`}</span><div><span>Page {currentPage} of {pageCount}</span><button className="icon-button" aria-label="Previous page" disabled={currentPage === 1 || loading} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={16} /></button><button className="icon-button" aria-label="Next page" disabled={currentPage >= pageCount || loading} onClick={() => setPage(currentPage + 1)}><ChevronRight size={16} /></button></div></div>
  </section>;
}
